DocumentRoot /var/www/html/public

<Directory /var/www/html/public>
    AllowOverride All
    Options -Indexes
    Require all granted
</Directory>

ServerTokens Prod
ServerSignature Off
ServerName localhost
